-- begin ATOMICBOTADMIN_NEWS_ITEM
alter table ATOMICBOTADMIN_NEWS_ITEM add constraint FK_ATOMICBOTADMIN_NEWS_ITEM_ON_IMAGE foreign key (IMAGE_ID) references SYS_FILE(ID)^
create index IDX_ATOMICBOTADMIN_NEWS_ITEM_ON_IMAGE on ATOMICBOTADMIN_NEWS_ITEM (IMAGE_ID)^
-- end ATOMICBOTADMIN_NEWS_ITEM
